### ISSUE TITLE
Hola Fran, soy Manu

### ISSUE THREAD

**Issue by Makova** [franlu/ReglajesF1#1]
¿Dónde esta el **reglajesf1.jar**?. También preguntarte si lo has forkeado de otro repo o si tienes otra fuente para poder consultarla, si es que existe :+1: 
Gracias y saludos makina.

**Comment by Makova** [comment]
Ups!!!

**Comment by franlu** [comment]
Hola @Makova,

En [SAD_F1.pdf](https://github.com/franlu/ReglajesF1/blob/master/doc/SAD_F1.pdf) escribo sobre reglajesf1.jar, ya que en 2008 la aplicación la escribí con Java. La versión que hay en el repositorio es la misma pero con Python. No necesitas ningún fichero *.jar :wink: 
No esta forkeado. Las fuentes de consulta son información genérica sobre F1 y ELECTRE.

s2!

**Comment by Makova** [comment]
¡¡Gracias!! :+1:
